// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSurjA2xnqVIP5-5eiELylyyVPqhxFOzs',
    appId: '1:934488907844:web:7a0ec3d91c1363b45e1c11',
    messagingSenderId: '934488907844',
    projectId: 'timetailor-dd0aa',
    authDomain: 'timetailor-dd0aa.firebaseapp.com',
    storageBucket: 'timetailor-dd0aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKcGh29C0uTQLF9l5IDvckME-Q31SVdd4',
    appId: '1:934488907844:android:abe0475b04c4e5d95e1c11',
    messagingSenderId: '934488907844',
    projectId: 'timetailor-dd0aa',
    storageBucket: 'timetailor-dd0aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwcsbEGFKA7w5QZDRoKEh9unW-92evyLM',
    appId: '1:934488907844:ios:66eee124e32c83195e1c11',
    messagingSenderId: '934488907844',
    projectId: 'timetailor-dd0aa',
    storageBucket: 'timetailor-dd0aa.firebasestorage.app',
    iosBundleId: 'com.example.timetailor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwcsbEGFKA7w5QZDRoKEh9unW-92evyLM',
    appId: '1:934488907844:ios:66eee124e32c83195e1c11',
    messagingSenderId: '934488907844',
    projectId: 'timetailor-dd0aa',
    storageBucket: 'timetailor-dd0aa.firebasestorage.app',
    iosBundleId: 'com.example.timetailor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSurjA2xnqVIP5-5eiELylyyVPqhxFOzs',
    appId: '1:934488907844:web:bffc89b3036bd7825e1c11',
    messagingSenderId: '934488907844',
    projectId: 'timetailor-dd0aa',
    authDomain: 'timetailor-dd0aa.firebaseapp.com',
    storageBucket: 'timetailor-dd0aa.firebasestorage.app',
  );
}
